spring:
  application:
    name: demo

  datasource:
    url: jdbc:mysql://localhost:3306/taskdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: taskuser
    password: taskpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          time_zone: UTC

  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600s

# define rocketmq properties here
rocketmq:
  name-server: localhost:9876
  producer:
    group: user-points-producer

demo:
  cache:
    points-ttl-seconds: 600
    load-lock-retry: 3
    load-lock-ttl-ms: 3000
    load-lock-wait-ms: 500
    load-lock-sleep-ms: 50
  mq:
    user-points-topic: user-points-topic
  leaderboard:
    refresh-ms: 10000
